//this file was autogenerated by makeRes
//makeRes -i ./Cadencii/Resources.list -o ./Cadencii/Resources.cs -p org.kbinani.cadencii -n org.kbinani.cadencii
package org.kbinani.cadencii;

import org.kbinani.*;

import java.awt.*;

import java.io.*;

import javax.imageio.*;

import javax.swing.*;


public class Resources {
    private static String superPath = null;
    private static Image s_alarm_clock = null;
    private static Image s_arrow_090 = null;
    private static Image s_arrow_180 = null;
    private static Image s_arrow_270 = null;
    private static Image s_arrow_skip_090 = null;
    private static Image s_arrow_135 = null;
    private static Image s_arrow_circle_double = null;
    private static Image s_arrow_return = null;
    private static Image s_arrow_skip = null;
    private static Image s_arrow_skip_180 = null;
    private static Image s_btn1 = null;
    private static Image s_btn2 = null;
    private static Image s_btn3 = null;
    private static Image s_chevron_small_collapse = null;
    private static Image s_clipboard_paste = null;
    private static Image s_control = null;
    private static Image s_control_double = null;
    private static Image s_control_double_180 = null;
    private static Image s_control_pause = null;
    private static Image s_control_skip = null;
    private static Image s_control_stop = null;
    private static Image s_control_stop_180 = null;
    private static Image s_cross_small = null;
    private static Image s_disk = null;
    private static Image s_disk__plus = null;
    private static Image s_documents = null;
    private static Image s_drive = null;
    private static Image s_edit_list_order = null;
    private static Image s_end_marker = null;
    private static Image s_eraser = null;
    private static Image s_folder__plus = null;
    private static Image s_folder = null;
    private static Image s_folder_horizontal_open = null;
    private static Image s_layer_shape_curve = null;
    private static Image s_layer_shape_line = null;
    private static Image s_pencil = null;
    private static Image s_piano = null;
    private static Image s_pin__arrow = null;
    private static Image s_pin__arrow_inv = null;
    private static Image s_ruler_crop = null;
    private static Image s_scissors = null;
    private static Image s_slash = null;
    private static Image s_start_marker = null;
    private static Image s_target__pencil = null;
    private static Image s_VSTonWht = null;
    private static Image s_icon = null;
    private static Image s_switch = null;
    private static Image s_cresc1 = null;
    private static Image s_cresc2 = null;
    private static Image s_cresc3 = null;
    private static Image s_cresc4 = null;
    private static Image s_cresc5 = null;
    private static Image s_dim1 = null;
    private static Image s_dim2 = null;
    private static Image s_dim3 = null;
    private static Image s_dim4 = null;
    private static Image s_dim5 = null;
    private static Image s_splash = null;
    private static Image s_plus8x8 = null;
    private static Image s_minus8x8 = null;

    public static void setBasePath(String value) {
       superPath = value;
    }

    private static String getBasePath() {
        if (superPath == null) {
            superPath = Resources.class.getResource("/assets/").toString();
        }
        return null;
    }

    private static InputStream getAsset(String relPath) {
        InputStream inputStream = Resources.class.getResourceAsStream("/assets" + relPath);
        return inputStream;
    }
    
    public static Image get_alarm_clock() {
        if (s_alarm_clock == null) {
            String res_path = fsys.combine(getBasePath(), "alarm-clock.png");
            try {
                s_alarm_clock = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_alarm_clock; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_alarm_clock;
    }

    public static Image get_arrow_090() {
        if (s_arrow_090 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow-090.png");

            try {
                s_arrow_090 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_090; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_090;
    }

    public static Image get_arrow_180() {
        if (s_arrow_180 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow-180.png");

            try {
                s_arrow_180 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_180; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_180;
    }

    public static Image get_arrow_270() {
        if (s_arrow_270 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow-270.png");

            try {
                s_arrow_270 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_270; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_270;
    }

    public static Image get_arrow_skip_090() {
        if (s_arrow_skip_090 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow-skip-090.png");

            try {
                s_arrow_skip_090 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_skip_090; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_skip_090;
    }

    public static Image get_arrow_135() {
        if (s_arrow_135 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow_135.png");

            try {
                s_arrow_135 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_135; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_135;
    }

    public static Image get_arrow_circle_double() {
        if (s_arrow_circle_double == null) {
            String res_path = fsys.combine(getBasePath(),
                    "arrow_circle_double.png");

            try {
                s_arrow_circle_double = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_circle_double; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_circle_double;
    }

    public static Image get_arrow_return() {
        if (s_arrow_return == null) {
            String res_path = fsys.combine(getBasePath(), "arrow_return.png");

            try {
                s_arrow_return = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_return; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_return;
    }

    public static Image get_arrow_skip() {
        if (s_arrow_skip == null) {
            String res_path = fsys.combine(getBasePath(), "arrow_skip.png");

            try {
                s_arrow_skip = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_skip; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_skip;
    }

    public static Image get_arrow_skip_180() {
        if (s_arrow_skip_180 == null) {
            String res_path = fsys.combine(getBasePath(), "arrow_skip_180.png");

            try {
                s_arrow_skip_180 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_arrow_skip_180; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_arrow_skip_180;
    }

    public static Image get_btn1() {
        if (s_btn1 == null) {
            String res_path = fsys.combine(getBasePath(), "btn1.png");

            try {
                s_btn1 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_btn1; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_btn1;
    }

    public static Image get_btn2() {
        if (s_btn2 == null) {
            String res_path = fsys.combine(getBasePath(), "btn2.png");

            try {
                s_btn2 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_btn2; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_btn2;
    }

    public static Image get_btn3() {
        if (s_btn3 == null) {
            String res_path = fsys.combine(getBasePath(), "btn3.png");

            try {
                s_btn3 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_btn3; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_btn3;
    }

    public static Image get_chevron_small_collapse() {
        if (s_chevron_small_collapse == null) {
            String res_path = fsys.combine(getBasePath(),
                    "chevron-small-collapse.png");

            try {
                s_chevron_small_collapse = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_chevron_small_collapse; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_chevron_small_collapse;
    }

    public static Image get_clipboard_paste() {
        if (s_clipboard_paste == null) {
            String res_path = fsys.combine(getBasePath(), "clipboard_paste.png");

            try {
                s_clipboard_paste = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_clipboard_paste; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_clipboard_paste;
    }

    public static Image get_control() {
        if (s_control == null) {
            String res_path = fsys.combine(getBasePath(), "control.png");

            try {
                s_control = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_control;
    }

    public static Image get_control_double() {
        if (s_control_double == null) {
            String res_path = fsys.combine(getBasePath(), "control_double.png");

            try {
                s_control_double = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_double; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_double;
    }

    public static Image get_control_double_180() {
        if (s_control_double_180 == null) {
            String res_path = fsys.combine(getBasePath(),
                    "control_double_180.png");

            try {
                s_control_double_180 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_double_180; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_double_180;
    }

    public static Image get_control_pause() {
        if (s_control_pause == null) {
            String res_path = fsys.combine(getBasePath(), "control_pause.png");

            try {
                s_control_pause = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_pause; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_pause;
    }

    public static Image get_control_skip() {
        if (s_control_skip == null) {
            String res_path = fsys.combine(getBasePath(), "control_skip.png");

            try {
                s_control_skip = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_skip; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_skip;
    }

    public static Image get_control_stop() {
        if (s_control_stop == null) {
            String res_path = fsys.combine(getBasePath(), "control_stop.png");

            try {
                s_control_stop = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_stop; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_stop;
    }

    public static Image get_control_stop_180() {
        if (s_control_stop_180 == null) {
            String res_path = fsys.combine(getBasePath(), "control_stop_180.png");

            try {
                s_control_stop_180 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_control_stop_180; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_control_stop_180;
    }

    public static Image get_cross_small() {
        if (s_cross_small == null) {
            String res_path = fsys.combine(getBasePath(), "cross-small.png");

            try {
                s_cross_small = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cross_small; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_cross_small;
    }

    public static Image get_disk() {
        if (s_disk == null) {
            String res_path = fsys.combine(getBasePath(), "disk.png");

            try {
                s_disk = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_disk; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_disk;
    }

    public static Image get_disk__plus() {
        if (s_disk__plus == null) {
            String res_path = fsys.combine(getBasePath(), "disk__plus.png");

            try {
                s_disk__plus = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_disk__plus; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_disk__plus;
    }

    public static Image get_documents() {
        if (s_documents == null) {
            String res_path = fsys.combine(getBasePath(), "documents.png");

            try {
                s_documents = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_documents; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_documents;
    }

    public static Image get_drive() {
        if (s_drive == null) {
            String res_path = fsys.combine(getBasePath(), "drive.png");

            try {
                s_drive = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_drive; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_drive;
    }

    public static Image get_edit_list_order() {
        if (s_edit_list_order == null) {
            String res_path = fsys.combine(getBasePath(), "edit-list-order.png");

            try {
                s_edit_list_order = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_edit_list_order; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_edit_list_order;
    }

    public static Image get_end_marker() {
        if (s_end_marker == null) {
            String res_path = fsys.combine(getBasePath(), "end_marker.png");

            try {
                s_end_marker = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_end_marker; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_end_marker;
    }

    public static Image get_eraser() {
        if (s_eraser == null) {
            String res_path = fsys.combine(getBasePath(), "eraser.png");

            try {
                s_eraser = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_eraser; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_eraser;
    }

    public static Image get_folder__plus() {
        if (s_folder__plus == null) {
            String res_path = fsys.combine(getBasePath(), "folder--plus.png");

            try {
                s_folder__plus = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_folder__plus; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_folder__plus;
    }

    public static Image get_folder() {
        if (s_folder == null) {
            String res_path = fsys.combine(getBasePath(), "folder.png");

            try {
                s_folder = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_folder; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_folder;
    }

    public static Image get_folder_horizontal_open() {
        if (s_folder_horizontal_open == null) {
            String res_path = fsys.combine(getBasePath(),
                    "folder_horizontal_open.png");

            try {
                s_folder_horizontal_open = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_folder_horizontal_open; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_folder_horizontal_open;
    }

    public static Image get_layer_shape_curve() {
        if (s_layer_shape_curve == null) {
            String res_path = fsys.combine(getBasePath(),
                    "layer_shape_curve.png");

            try {
                s_layer_shape_curve = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_layer_shape_curve; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_layer_shape_curve;
    }

    public static Image get_layer_shape_line() {
        if (s_layer_shape_line == null) {
            String res_path = fsys.combine(getBasePath(), "layer_shape_line.png");

            try {
                s_layer_shape_line = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_layer_shape_line; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_layer_shape_line;
    }

    public static Image get_pencil() {
        if (s_pencil == null) {
            String res_path = fsys.combine(getBasePath(), "pencil.png");

            try {
                s_pencil = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_pencil; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_pencil;
    }

    public static Image get_piano() {
        if (s_piano == null) {
            String res_path = fsys.combine(getBasePath(), "piano.png");

            try {
                s_piano = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_piano; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_piano;
    }

    public static Image get_pin__arrow() {
        if (s_pin__arrow == null) {
            String res_path = fsys.combine(getBasePath(), "pin__arrow.png");

            try {
                s_pin__arrow = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_pin__arrow; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_pin__arrow;
    }

    public static Image get_pin__arrow_inv() {
        if (s_pin__arrow_inv == null) {
            String res_path = fsys.combine(getBasePath(), "pin__arrow_inv.png");

            try {
                s_pin__arrow_inv = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_pin__arrow_inv; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_pin__arrow_inv;
    }

    public static Image get_ruler_crop() {
        if (s_ruler_crop == null) {
            String res_path = fsys.combine(getBasePath(), "ruler_crop.png");

            try {
                s_ruler_crop = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_ruler_crop; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_ruler_crop;
    }

    public static Image get_scissors() {
        if (s_scissors == null) {
            String res_path = fsys.combine(getBasePath(), "scissors.png");

            try {
                s_scissors = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_scissors; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_scissors;
    }

    public static Image get_slash() {
        if (s_slash == null) {
            String res_path = fsys.combine(getBasePath(), "slash.png");

            try {
                s_slash = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_slash; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_slash;
    }

    public static Image get_start_marker() {
        if (s_start_marker == null) {
            String res_path = fsys.combine(getBasePath(), "start_marker.png");

            try {
                s_start_marker = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_start_marker; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_start_marker;
    }

    public static Image get_target__pencil() {
        if (s_target__pencil == null) {
            String res_path = fsys.combine(getBasePath(), "target--pencil.png");

            try {
                s_target__pencil = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_target__pencil; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_target__pencil;
    }

    public static Image get_VSTonWht() {
        if (s_VSTonWht == null) {
            String res_path = fsys.combine(getBasePath(), "VSTonWht.png");

            try {
                s_VSTonWht = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_VSTonWht; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_VSTonWht;
    }

    public static Image get_icon() {
        if (s_icon == null) {
            String res_path = fsys.combine(getBasePath(), "icon.ico");

            try {
                s_icon = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_icon; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_icon;
    }

    public static Image get_switch() {
        if (s_switch == null) {
            String res_path = fsys.combine(getBasePath(), "switch.ico");

            try {
                s_switch = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_switch; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_switch;
    }

    public static Image get_cresc1() {
        if (s_cresc1 == null) {
            String res_path = fsys.combine(getBasePath(), "cresc1.png");

            try {
                s_cresc1 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cresc1; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_cresc1;
    }

    public static Image get_cresc2() {
        if (s_cresc2 == null) {
            String res_path = fsys.combine(getBasePath(), "cresc2.png");

            try {
                s_cresc2 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cresc2; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_cresc2;
    }

    public static Image get_cresc3() {
        if (s_cresc3 == null) {
            String res_path = fsys.combine(getBasePath(), "cresc3.png");

            try {
                s_cresc3 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cresc3; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_cresc3;
    }

    public static Image get_cresc4() {
        if (s_cresc4 == null) {
            String res_path = fsys.combine(getBasePath(), "cresc4.png");

            try {
                s_cresc4 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cresc4; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_cresc4;
    }

    public static Image get_cresc5() {
        if (s_cresc5 == null) {
            String res_path = fsys.combine(getBasePath(), "cresc5.png");

            try {
                s_cresc5 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_cresc5; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_cresc5;
    }

    public static Image get_dim1() {
        if (s_dim1 == null) {
            String res_path = fsys.combine(getBasePath(), "dim1.png");

            try {
                s_dim1 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_dim1; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_dim1;
    }

    public static Image get_dim2() {
        if (s_dim2 == null) {
            String res_path = fsys.combine(getBasePath(), "dim2.png");

            try {
                s_dim2 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_dim2; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_dim2;
    }

    public static Image get_dim3() {
        if (s_dim3 == null) {
            String res_path = fsys.combine(getBasePath(), "dim3.png");

            try {
                s_dim3 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_dim3; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_dim3;
    }

    public static Image get_dim4() {
        if (s_dim4 == null) {
            String res_path = fsys.combine(getBasePath(), "dim4.png");

            try {
                s_dim4 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_dim4; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_dim4;
    }

    public static Image get_dim5() {
        if (s_dim5 == null) {
            String res_path = fsys.combine(getBasePath(), "dim5.png");

            try {
                s_dim5 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_dim5; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_dim5;
    }

    public static Image get_splash() {
        if (s_splash == null) {
            String res_path = fsys.combine(getBasePath(), "splash.png");

            try {
                s_splash = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_splash; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_splash;
    }

    public static Image get_plus8x8() {
        if (s_plus8x8 == null) {
            String res_path = fsys.combine(getBasePath(), "plus8x8.png");

            try {
                s_plus8x8 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_plus8x8; ex=" + ex + "; res_path=" +
                    res_path);
            }
        }

        return s_plus8x8;
    }

    public static Image get_minus8x8() {
        if (s_minus8x8 == null) {
            String res_path = fsys.combine(getBasePath(), "minus8x8.png");

            try {
                s_minus8x8 = ImageIO.read(getAsset(res_path));
            } catch (Exception ex) {
                serr.println("Resources#get_minus8x8; ex=" + ex +
                    "; res_path=" + res_path);
            }
        }

        return s_minus8x8;
    }
}
